# INSEGURO: re-habilita TLS 1.0 / 1.1 en Java 17 quitándolos de la lista de deshabilitados
# Mantiene bloqueos de cosas muy malas como SSLv3/RC4/DES, etc.
jdk.tls.disabledAlgorithms=SSLv3, RC4, DES, MD5withRSA, DH keySize < 1024, EC keySize < 224, 3DES_EDE_CBC, anon, NULL
